### ISSUE TITLE
Project Sidewalk project page gives 500 server error

### ISSUE THREAD

**Issue by misaugstad** [makeabilitylab/makeabilitylabwebsite#1003]
Going to https://makeabilitylab.cs.washington.edu/project/sidewalk/ just gives `Server Error (500)`. I tried ~10 other project pages, and this was the only one that had that issue.

**Comment by jonfroehlich** [comment]
Also mentioned by 
![image](https://user-images.githubusercontent.com/1621749/163433237-7d30bcc9-6b6c-48e0-855d-09f84802f756.png)

And Jen recently emailed me about it. I just won't have time to fix until Summer. :-/

**Comment by jonfroehlich** [comment]
Just checked the error log

```
ERROR 2022-04-15 09:10:51,733 log log_response 396 140490192189184 Internal Server Error: /project/sidewalk/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/website/views/project.py", line 39, in project
    project_roles_past = sorted(project_roles_past, key=attrgetter('end_date'), reverse=True)
TypeError: '<' not supported between instances of 'datetime.date' and 'NoneType'
ERROR 2022-04-15 09:10:51,734 basehttp log_message 396 140490192189184 "GET /project/sidewalk/ HTTP/1.1" 500 145
```

**Comment by jonfroehlich** [comment]
I think I figured it out. We are using `is_active()` on `project_roles` to determine if someone has finished their researchship/internship with us but this doesn't work for when we have a start date for a future date (from today).

Updating...

**Comment by jonfroehlich** [comment]
Now on to a new error

```

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/website/views/project.py", line 80, in project
    project_role_with_title.sort(key=attrgetter('end_date'), reverse=True)
TypeError: '<' not supported between instances of 'datetime.date' and 'NoneType'
```

**Comment by jonfroehlich** [comment]
Wo0t. Fixed it!

https://makeabilitylab.cs.washington.edu/project/sidewalk/

This series of commits

![image](https://user-images.githubusercontent.com/1621749/163651631-0d55a30b-b553-48f9-ad5d-68ce928c5266.png)
