### ISSUE TITLE
When you try to add an author in a pub page, the pop-up modal does not auto-close

### ISSUE THREAD

**Issue by jonfroehlich** [makeabilitylab/makeabilitylabwebsite#1014]
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/1621749/199103247-1b1ba17f-4ced-4072-8f6c-e49c825360b3.png">

```
:8571/static/admin/js/SelectBox.js:56 Uncaught TypeError: Cannot read properties of undefined (reading 'push')
    at Object.add_to_cache (:8571/static/admin/js/SelectBox.js:56:33)
    at dismissAddRelatedObjectPopup (:8571/static/admin/js/admin/RelatedObjectLookups.js:140:23)
    at window.<computed> (:8571/static/sortedm2m/widget.js:131:58)
    at popup_response.js:13:16
```

Maybe a bug in sortedm2m widget? But the unfortunate part is that this has been happening for years--over many versions...

**Comment by jonfroehlich** [comment]
Duplicate of: https://github.com/makeabilitylab/makeabilitylabwebsite/issues/973
