### ISSUE TITLE
website.models.video.Video.publication.RelatedObjectDoesNotExist: Video has no publication

### ISSUE THREAD

**Issue by jonfroehlich** [makeabilitylab/makeabilitylabwebsite#1017]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [pdf_file] in None
DEBUG 2022-11-01 16:41:20,187 base _resolve_lookup 460 140069540534016 Exception while resolving variable 'publication' in template 'website/index.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
TypeError: 'Video' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 461, in __get__
    raise self.RelatedObjectDoesNotExist(
website.models.video.Video.publication.RelatedObjectDoesNotExist: Video has no publication
```

Looks like this is related to: https://stackoverflow.com/a/40743258

We have 

```
{% if video.publication %}
                | <a href="../../media/{{ video.publication.pdf_file }}">Paper</a>
            {% endif %}
```
in `display_video_snippet.html` that is the offending issue

**Comment by jonfroehlich** [comment]
I believe this is fixed with https://github.com/makeabilitylab/makeabilitylabwebsite/issues/1017
