### ISSUE TITLE
Can't link posters, videos, talks, on pub admin interface

### ISSUE THREAD

**Issue by jonfroehlich** [makeabilitylab/makeabilitylabwebsite#1093]
There is a bug here for sure:

![image](https://github.com/makeabilitylab/makeabilitylabwebsite/assets/1621749/d0241895-1eff-464d-beed-cc6c63021482)

[Link](https://makeabilitylab.cs.washington.edu/admin/website/publication/668/change/)

**Comment by jonfroehlich** [comment]
When I open the console, I'm getting:

![image](https://github.com/makeabilitylab/makeabilitylabwebsite/assets/1621749/826d1ae9-711d-4f6d-9ddc-58180bfac046)


```
en.js:3 Uncaught TypeError: Cannot read properties of undefined (reading 'define')
    at en.js:3:106
    at en.js:3:755
(anonymous) @ en.js:3
(anonymous) @ en.js:3
jquery.min.js:16 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at Function.each (jquery.min.js:16:11175)
    at prepopulate_init.js:5:7
each @ jquery.min.js:16
(anonymous) @ prepopulate_init.js:5
autocomplete.js:7 Uncaught TypeError: $(...).select2 is not a function
    at HTMLSelectElement.<anonymous> (autocomplete.js:7:24)
    at Function.each (jquery.min.js:16:11390)
    at $.fn.djangoAdminSelect2 (autocomplete.js:6:11)
    at HTMLDocument.<anonymous> (autocomplete.js:27:60)
    at Object.resolveWith (jquery.min.js:16:14211)
    at Function.ready (jquery.min.js:16:9196)
    at HTMLDocument.y (jquery.min.js:16:13679)
(anonymous) @ autocomplete.js:7
each @ jquery.min.js:16
$.fn.djangoAdminSelect2 @ autocomplete.js:6
(anonymous) @ autocomplete.js:27
resolveWith @ jquery.min.js:16
ready @ jquery.min.js:16
y @ jquery.min.js:16
:8571/favicon.ico:1 
        
        
       GET http://localhost:8571/favicon.ico 500 (Internal Server Error)
```

But the weird thing is, select2 is not installed!

If I go into the Docker instance and try to find select2 stuff, it's showing up!

```
jonf@jonfhome:~$ docker exec -it -u root 00496813ffb5 /bin/bash
root@00496813ffb5:/usr/local/lib/python3.11/site-packages# find / -name "select2.full.js"
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/js/vendor/select2/select2.full.js
/code/static/admin/js/vendor/select2/select2.full.js
```

So I tried deleting it:

```
root@00496813ffb5:/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/js/vendor# rm -rf select2
```

And then ran it again:

```
root@00496813ffb5:/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/js/vendor# find / -name "select2" 2>/dev/null
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/vendor/select2
/code/static/admin/js/vendor/select2
/code/static/admin/css/vendor/select2

root@00496813ffb5:/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/js/vendor# find / -name "select2" 2>/dev/null
/code/static/admin/js/vendor/select2
/code/static/admin/css/vendor/select2

root@00496813ffb5:/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/js/vendor# rm -rf /code/static/admin/js/vendor/select2
root@00496813ffb5:/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/js/vendor# rm -rf /code/static/admin/css/vendor/select2
root@00496813ffb5:/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/js/vendor# find / -name "select2" 2>/dev/null
root@00496813ffb5:/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/js/vendor#
```

**Comment by jonfroehlich** [comment]
Ugh, still not working. When I look at the `<head>` in the html admin, I see that it's trying to load select2.css

![image](https://github.com/makeabilitylab/makeabilitylabwebsite/assets/1621749/8d7ef4d9-7a11-43ac-93fa-e0bc17a963c3)

**Comment by jonfroehlich** [comment]
So then I thought to try and look at the raw html in Django to see how this header is put together.

```
root@00496813ffb5:/usr/local/lib/python3.11/site-packages/django/contrib/admin/templates/admin
root@00496813ffb5:/usr/local/lib/python3.11/site-packages/django/contrib/admin/templates/admin# ls -al
total 136
drwxr-xr-x 6 root root 4096 Sep 25 13:24 .
drwxr-xr-x 4 root root 4096 Sep 25 13:24 ..
-rw-r--r-- 1 root root  282 Sep 25 13:24 404.html
-rw-r--r-- 1 root root  551 Sep 25 13:24 500.html
-rw-r--r-- 1 root root 1235 Sep 25 13:24 actions.html
-rw-r--r-- 1 root root  493 Sep 25 13:24 app_index.html
-rw-r--r-- 1 root root 1716 Sep 25 13:24 app_list.html
drwxr-xr-x 3 root root 4096 Sep 25 13:24 auth
-rw-r--r-- 1 root root 6110 Sep 25 13:24 base.html
-rw-r--r-- 1 root root  448 Sep 25 13:24 base_site.html
-rw-r--r-- 1 root root 3019 Sep 25 13:24 change_form.html
-rw-r--r-- 1 root root  403 Sep 25 13:24 change_form_object_tools.html
-rw-r--r-- 1 root root 3290 Sep 25 13:24 change_list.html
-rw-r--r-- 1 root root  378 Sep 25 13:24 change_list_object_tools.html
-rw-r--r-- 1 root root 1502 Sep 25 13:24 change_list_results.html
-rw-r--r-- 1 root root  697 Sep 25 13:24 color_theme_toggle.html
-rw-r--r-- 1 root root  453 Sep 25 13:24 date_hierarchy.html
-rw-r--r-- 1 root root 2539 Sep 25 13:24 delete_confirmation.html
-rw-r--r-- 1 root root 2241 Sep 25 13:24 delete_selected_confirmation.html
drwxr-xr-x 2 root root 4096 Sep 25 13:24 edit_inline
-rw-r--r-- 1 root root  395 Sep 25 13:24 filter.html
drwxr-xr-x 2 root root 4096 Sep 25 13:24 includes
-rw-r--r-- 1 root root 1849 Sep 25 13:24 index.html
-rw-r--r-- 1 root root  447 Sep 25 13:24 invalid_setup.html
-rw-r--r-- 1 root root 1899 Sep 25 13:24 login.html
-rw-r--r-- 1 root root  486 Sep 25 13:24 nav_sidebar.html
-rw-r--r-- 1 root root 2136 Sep 25 13:24 object_history.html
-rw-r--r-- 1 root root  549 Sep 25 13:24 pagination.html
-rw-r--r-- 1 root root  327 Sep 25 13:24 popup_response.html
-rw-r--r-- 1 root root  209 Sep 25 13:24 prepopulated_fields_js.html
-rw-r--r-- 1 root root 1257 Sep 25 13:24 search_form.html
-rw-r--r-- 1 root root 1093 Sep 25 13:24 submit_line.html
drwxr-xr-x 2 root root 4096 Sep 25 13:24 widgets
```

I looked at base.html, change_form.html, etc. and they all looked as expected. select2.css was not in there.

Here's part of base.html

```
{% load i18n static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" dir="{{ LANGUAGE_BIDI|yesno:'rtl,ltr,auto' }}">
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}">
{% block dark-mode-vars %}
  <link rel="stylesheet" href="{% static "admin/css/dark_mode.css" %}">
  <script src="{% static "admin/js/theme.js" %}" defer></script>
{% endblock %}
{% if not is_popup and is_nav_sidebar_enabled %}
  <link rel="stylesheet" href="{% static "admin/css/nav_sidebar.css" %}">
  <script src="{% static 'admin/js/nav_sidebar.js' %}" defer></script>
{% endif %}
{% block extrastyle %}{% endblock %}
{% if LANGUAGE_BIDI %}<link rel="stylesheet" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}">{% endif %}
{% block extrahead %}{% endblock %}
{% block responsive %}
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" href="{% static "admin/css/responsive.css" %}">
    {% if LANGUAGE_BIDI %}<link rel="stylesheet" href="{% static "admin/css/responsive_rtl.css" %}">{% endif %}
{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE">{% endblock %}
</head>
```

So, I might post to Stackoverflow or clear my pycache as next steps.

**Comment by jonfroehlich** [comment]
Hrm, I decided to look for select2 in the base Django files and, indeed, found it. It turns out that "Django’s admin comes with builtin support for Select2 via the [autocomplete_fields](https://docs.djangoproject.com/en/stable/ref/contrib/admin/#django.contrib.admin.ModelAdmin.autocomplete_fields) feature." See: https://pypi.org/project/django-select2/. So maybe this whole thing has been a wild goose chase and something else is going on!

```
root@00496813ffb5:/usr/local/lib/python3.11/site-packages/django/contrib# sudo grep -r "select2" /usr/local/lib/python3.11/site-packages/django/
grep: /usr/local/lib/python3.11/site-packages/django/contrib/admin/__pycache__/widgets.cpython-311.pyc: binary file matches
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js:        selects.next().find('.select2-selection__rendered').each(function() {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/js/autocomplete.js:            $(element).select2({
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete.select2-container {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-selection--single,
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-selection--multiple {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete.select2-container--focus .select2-selection,
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete.select2-container--open .select2-selection {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete.select2-container--focus .select2-selection.select2-selection--single,
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete.select2-container--open .select2-selection.select2-selection--single {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete.select2-container--focus .select2-selection.select2-selection--multiple,
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete.select2-container--open .select2-selection.select2-selection--multiple {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-selection--single {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-selection--single .select2-selection__rendered {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-selection--single .select2-selection__clear {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-selection--single .select2-selection__placeholder {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-selection--single .select2-selection__arrow {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-selection--single .select2-selection__arrow b {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete[dir="rtl"] .select2-selection--single .select2-selection__clear {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete[dir="rtl"] .select2-selection--single .select2-selection__arrow {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete.select2-container--disabled .select2-selection--single {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete.select2-container--disabled .select2-selection--single .select2-selection__clear {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete.select2-container--open .select2-selection--single .select2-selection__arrow b {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-selection--multiple {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-selection--multiple .select2-selection__rendered {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-selection--multiple .select2-selection__rendered li {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-selection--multiple .select2-selection__placeholder {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-selection--multiple .select2-selection__clear {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-selection--multiple .select2-selection__choice {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-selection--multiple .select2-selection__choice__remove {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-selection--multiple .select2-selection__choice__remove:hover {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete[dir="rtl"] .select2-selection--multiple .select2-selection__choice, .select2-container--admin-autocomplete[dir="rtl"] .select2-selection--multiple .select2-selection__placeholder, .select2-container--admin-autocomplete[dir="rtl"] .select2-selection--multiple .select2-search--inline {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete[dir="rtl"] .select2-selection--multiple .select2-selection__choice {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete[dir="rtl"] .select2-selection--multiple .select2-selection__choice__remove {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete.select2-container--focus .select2-selection--multiple {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete.select2-container--disabled .select2-selection--multiple {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete.select2-container--disabled .select2-selection__choice__remove {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete.select2-container--open.select2-container--above .select2-selection--single, .select2-container--admin-autocomplete.select2-container--open.select2-container--above .select2-selection--multiple {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete.select2-container--open.select2-container--below .select2-selection--single, .select2-container--admin-autocomplete.select2-container--open.select2-container--below .select2-selection--multiple {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-search--dropdown {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-search--dropdown .select2-search__field {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-search--inline .select2-search__field {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-results > .select2-results__options {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-results__option[role=group] {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-results__option[aria-disabled=true] {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-results__option[aria-selected=true] {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-results__option .select2-results__option {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-results__option .select2-results__option .select2-results__group {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-results__option .select2-results__option .select2-results__option {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-results__option .select2-results__option .select2-results__option .select2-results__option {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-results__option .select2-results__option .select2-results__option .select2-results__option .select2-results__option {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-results__option .select2-results__option .select2-results__option .select2-results__option .select2-results__option .select2-results__option {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-results__option .select2-results__option .select2-results__option .select2-results__option .select2-results__option .select2-results__option .select2-results__option {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-results__option--highlighted[aria-selected] {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/static/admin/css/autocomplete.css:.select2-container--admin-autocomplete .select2-results__group {
/usr/local/lib/python3.11/site-packages/django/contrib/admin/widgets.py:# language codes supported by select2.
/usr/local/lib/python3.11/site-packages/django/contrib/admin/widgets.py:# See django/contrib/admin/static/admin/js/vendor/select2/i18n/*
/usr/local/lib/python3.11/site-packages/django/contrib/admin/widgets.py:def get_select2_language():
/usr/local/lib/python3.11/site-packages/django/contrib/admin/widgets.py:    Renders the necessary data attributes for select2 and adds the static form
/usr/local/lib/python3.11/site-packages/django/contrib/admin/widgets.py:        self.i18n_name = get_select2_language()
/usr/local/lib/python3.11/site-packages/django/contrib/admin/widgets.py:        Set select2's AJAX attributes.
/usr/local/lib/python3.11/site-packages/django/contrib/admin/widgets.py:        https://select2.org/configuration/data-attributes#nested-subkey-options
/usr/local/lib/python3.11/site-packages/django/contrib/admin/widgets.py:            ("admin/js/vendor/select2/i18n/%s.js" % self.i18n_name,)
/usr/local/lib/python3.11/site-packages/django/contrib/admin/widgets.py:                "admin/js/vendor/select2/select2.full%s.js" % extra,
/usr/local/lib/python3.11/site-packages/django/contrib/admin/widgets.py:                    "admin/css/vendor/select2/select2%s.css" % extra,
```

**Comment by jonfroehlich** [comment]
To be clear, https://github.com/makeabilitylab/makeabilitylabwebsite/commit/691259b98dfe880f23ed3f253e2f1e1a22cf69b6 does not fix anything... was just trying to clean up the code a bit to investigate...

**Comment by jonfroehlich** [comment]
In desparation, I asked on the [Django forums](https://forum.djangoproject.com/t/in-admin-interface-autocomplete-fields-not-working-and-triggering-javascript-errors/) but so far nothing.

So, I commented out the auto-complete fields and they are just ordinary drop-downs for now.

**Comment by jonfroehlich** [comment]
This is also happening in TalkAdmin

<img width="1397" alt="image" src="https://github.com/user-attachments/assets/e999ff81-b38a-4aee-a439-3cc3b6df020d">

The offending code is:

```
en.js:3 Uncaught TypeError: Cannot read properties of undefined (reading 'define')
    at en.js:3:106
    at en.js:3:755
(anonymous) @ en.js:3
(anonymous) @ en.js:3Understand this error
jquery.min.js:16 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at Function.each (jquery.min.js:16:11175)
    at prepopulate_init.js:5:7
each @ jquery.min.js:16
(anonymous) @ prepopulate_init.js:5Understand this error
autocomplete.js:7 Uncaught TypeError: $(...).select2 is not a function
    at HTMLSelectElement.<anonymous> (autocomplete.js:7:24)
    at Function.each (jquery.min.js:16:11390)
    at init.djangoAdminSelect2 (autocomplete.js:6:11)
    at HTMLDocument.<anonymous> (autocomplete.js:27:60)
    at Object.resolveWith (jquery.min.js:16:14211)
    at Function.ready (jquery.min.js:16:9196)
    at HTMLDocument.y (jquery.min.js:16:13679)
```

To fix this, I simply comment out this line in TalkAdmin but then that takes out the autocomplete functionality and turns the widget into a dropdown, which is cumbersome:

```
autocomplete_fields = ['video']
```

If I comment this out, it works again (but without autocomplete):
<img width="1402" alt="image" src="https://github.com/user-attachments/assets/0bf3d149-8e62-4dd4-9181-272de3989ae0">

**Comment by jonfroehlich** [comment]
This is now fixed.
