### ISSUE TITLE
Failed lookup for key [speakers]

### ISSUE THREAD

**Issue by jonfroehlich** [makeabilitylab/makeabilitylabwebsite#1185]
On the test server. Replicate by loading homepage.

Problem is likely in display_talk_snippet.html

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'Talk' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Talk' object has no attribute 'speakers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'speakers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [speakers] in <Talk: Unknown, 'Hybrid Spaces & Third Places: For Scientizing with Mobile, Wearabile, & Community Technologies', DUB Talk, 2018-02-13>
DEBUG 2024-09-24 06:14:50,532 utils debug_sql 770 140484210058944 (0.001) SELECT "website_publication"."id", "website_publication"."title", "website_publication"."date", "website_publication"."forum_name", "website_publication"."forum_url", "website_publication"."location", "website_publication"."pdf_file", "website_publication"."raw_file", "website_publication"."thumbnail", "website_publication"."book_title", "website_publication"."official_url", "website_publication"."video_id", "website_publication"."talk_id", "website_publication"."poster_id", "website_publication"."code_repo_url", "website_publication"."series", "website_publication"."isbn", "website_publication"."doi", "website_publication"."publisher", "website_publication"."publisher_address", "website_publication"."acmid", "website_publication"."num_pages", "website_publication"."page_num_start", "website_publication"."page_num_end", "website_publication"."pub_venue_type", "website_publication"."extended_abstract", "website_publication"."peer_reviewed", "website_publication"."total_papers_accepted", "website_publication"."total_papers_submitted", "website_publication"."award" FROM "website_publication" WHERE "website_publication"."talk_id" = 625; args=(625,); alias=default
DEBUG 2024-09-24 06:14:50,544 utils debug_sql 770 140484210058944 (0.001) SELECT "website_project"."id", "website_project"."name", "website_project"."short_name", "website_project"."start_date", "website_project"."end_date", "website_project"."featured_video_id", "website_project"."featured_code_repo_url", "website_project"."website", "website_project"."data_url", "website_project"."gallery_image", "website_project"."thumbnail_alt_text", "website_project"."cropping", "website_project"."summary", "website_project"."about", "website_project"."updated" FROM "website_project" INNER JOIN "website_talk_projects" ON ("website_project"."id" = "website_talk_projects"."project_id") WHERE "website_talk_projects"."talk_id" = 625; args=(625,); alias=default
DEBUG 2024-09-24 06:14:50,561 utils debug_sql 770 140484210058944 (0.003) SELECT "website_sponsor"."id", "website_sponsor"."name", "website_sponsor"."short_name", "website_sponsor"."icon", "website_sponsor"."alt_text", "website_sponsor"."icon_cropping", "website_sponsor"."url", COALESCE(SUM("website_grant"."funding_amount"), 0) AS "total_funding" FROM "website_sponsor" LEFT OUTER JOIN "website_grant" ON ("website_sponsor"."id" = "website_grant"."sponsor_id") GROUP BY "website_sponsor"."id" ORDER BY 8 DESC, "website_sponsor"."name" ASC; args=(0,); alias=default
DEBUG 2024-09-24 06:14:50,586 utils debug_sql 770 140484210058944 (0.001) SELECT "website_news"."id", "website_news"."title", "website_news"."slug", "website_news"."date", "website_news"."author_id", "website_news"."content", "website_news"."image", "website_news"."cropping", "website_news"."caption", "website_news"."alt_text" FROM "website_news" ORDER BY "website_news"."date" DESC LIMIT 3; args=(); alias=default
```

**Comment by jonfroehlich** [comment]
I think this might be because we switched speakers to authors when we did the Artifact refactor.

So, we should be referring to authors rather than speakers...

**Comment by jonfroehlich** [comment]
Looks like after we did our Artifact -> Talks refactor, we didn't change our access in talks from talks.speakers to talks.authors. So, I just added some convenience methods to Talk: get_speakers and has_speakers to duplicate this functionality but underneath they just call authors

https://github.com/makeabilitylab/makeabilitylabwebsite/commit/dd7f8988f9f71c213dbeb54ea0f709ad9534047a

**Comment by jonfroehlich** [comment]
Appears to work!
