### ISSUE TITLE
Running importpubs throws FileNotFoundError

### ISSUE THREAD

**Issue by jonfroehlich** [makeabilitylab/makeabilitylabwebsite#558]
I was able to get importpubs to work before but now I cannot. The error thrown is:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/code/website/management/commands/importpubs.py", line 188, in handle
    self.loadDatabase(bibtex_str)
  File "/code/website/management/commands/importpubs.py", line 339, in loadDatabase
    author_obj_list = get_authors(author_str_list)
  File "/code/website/management/commands/importpubs.py", line 63, in get_authors
    starwars = get_random_starwars(direc)
  File "/code/website/management/commands/importpubs.py", line 48, in get_random_starwars
    images = [f for f in os.listdir(direc) if isimage(f)]
FileNotFoundError: [Errno 2] No such file or directory: 'import/images/StarWarsFiguresFullSquare/Rebels/'
```

**Comment by jonfroehlich** [comment]
@aileenzeng, are you getting this error too as you test?

**Comment by jonfroehlich** [comment]
@johnsonkuang said he's going to look into this.

**Comment by jonfroehlich** [comment]
@johnsonkuang can we get a status update? We now have a few new Makeability Labbers actively working on the webpage (e.g., @htadeusiak) and this Issue remains critical--it would help us all better setup our local dev environments with content.

Can you give us a sense of what's holding you up and your ETA. You communicated with me over email stating that you're working on it...

**Comment by johnsonkuang** [comment]
Back from break, finishing up import command today, will push today.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jonfroehlich** [comment]
Great! Looking forward to seeing it. @htadeusiak can help us test!

**Comment by johnsonkuang** [comment]
I’ve come up with a problem while trying to run importpubs, it now creates and saves some publication objects but for some exceptions. These exceptions will throw these errors:
Publication 'iLearn on the iPhone: Real-Time Human Activity Classification on Commodity Mobile Phones' has just been saved with PDF=/code/media/publications/media/temp/iLearn_on_the_iPhone_Real_Time_Human_Activity_Classification_on_Commodity_Mobile_Phones_wKrou44.pdf, checking to see if we should auto-generate a thumbnail
Error: /syntaxerror in /----nostringval----
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   2045   1   3   %oparray_pop   2044   1   3   %oparray_pop   2025   1   3   %oparray_pop   1884   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push
Dictionary stack:
   --dict:967/1684(ro)(G)--   --dict:0/20(G)--   --dict:78/200(L)--
Current allocation mode is local
GPL Ghostscript 9.26: Unrecoverable error, exit code 1
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/code/website/management/commands/importpubs.py", line 94, in handle
    serializer.save()
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 728, in save
    self.instance = self.create(validated_data)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 700, in create
    self.child.create(attrs) for attrs in validated_data
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 700, in <listcomp>
    self.child.create(attrs) for attrs in validated_data
  File "/code/website/serializers.py", line 84, in create
    p = Publication.objects.create(pdf_file=pdf, thumbnail=thumbnail, **validated_data)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
 File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 417, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 769, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 178, in send
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/code/website/signals.py", line 37, in publication_post_save
    generate_and_save_thumbnail_from_pdf(pub, thumbnail_res)
  File "/code/website/signals.py", line 77, in generate_and_save_thumbnail_from_pdf
    img.format = 'jpeg'
  File "/usr/local/lib/python3.7/site-packages/wand/image.py", line 2932, in format
    raise ValueError(repr(fmt) + ' is unsupported format')
ValueError: 'jpeg' is unsupported format

I cannot resolve this problem despite trying to bypass this signal altogether. Nothing seems to work, I have tried ‘png’, ‘jpg’, ‘jpeg’, and any of the capitalizations of the previously mentioned file extensions. Has anyone encountered this error before?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jonfroehlich** [comment]
@johnsonkuang, is the 'iLearn on the iPhone: Real-Time Human Activity Classification on Commodity Mobile Phones' the only pub that messes up? Perhaps related to this Issue (https://github.com/jonfroehlich/makeabilitylabwebsite/issues/578#issuecomment-425596689)?

Let me re-upload the PDF and see what happens. Stay tuned.

**Comment by johnsonkuang** [comment]
I’m not too sure, I think it’s just that it needs to auto-generate a thumbnail for the pdf but the code doesn’t seem to work right now (i.e. the entered format doesn’t seem to be what ImageMagick is expecting)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jonfroehlich** [comment]
Does it work now? I re-uploaded the iLearn pdf (but only on the production site and not on the test site). I couldn't tell from your post whether you read my response (https://github.com/jonfroehlich/makeabilitylabwebsite/issues/558#issuecomment-450152881) and tried your code again.

**Comment by jonfroehlich** [comment]
I've also updated the priority level to 'Very High' for this Issue in general as we will have a set of new students working on the ML website in Winter'19 and getting this to work will greatly assist in setting up local dev environments.

**Comment by johnsonkuang** [comment]
Import pubs now works

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jonfroehlich** [comment]
What was wrong? What did you have to fix? Also, your PR is messed up: https://github.com/jonfroehlich/makeabilitylabwebsite/pull/592#issuecomment-450227504

**Comment by jonfroehlich** [comment]
@johnsonkuang, I see that you closed this PR (https://github.com/jonfroehlich/makeabilitylabwebsite/pull/592) but you didn't create a new one or respond to my questions above. Can you do that when you get a chance?

**Comment by jonfroehlich** [comment]
This is no longer relevant as my UMD page has been taken down. :)
