### ISSUE TITLE
On new Django 3.2.10 release on test server, getting wand error

### ISSUE THREAD

**Issue by jonfroehlich** [makeabilitylab/makeabilitylabwebsite#974]
When we upload a file, we receive this error:

```
wand.exceptions.PolicyError: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/421
```

There is a nice [StackOverflow ](https://stackoverflow.com/questions/52998331/imagemagick-security-policy-pdf-blocking-conversion) discussion of this problem and potential solutions. One recommended fix is [this](https://stackoverflow.com/a/59193253/388117):

![image](https://user-images.githubusercontent.com/1621749/146621923-46df5a4f-721f-4f71-964e-78454ab8ebb8.png)

Not sure how we could edit this policy.xml document on the server.

Full error:

```
ERROR 2021-12-17 16:15:34,991 log 396 140215633041152 Internal Server Error: /admin/website/publication/add/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1657, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1540, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1586, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1099, in save_model
    obj.save()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 787, in save_base
    post_save.send(
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/code/website/signals.py", line 37, in publication_post_save
    generate_and_save_thumbnail_from_pdf(pub, thumbnail_res)
  File "/code/website/signals.py", line 94, in generate_and_save_thumbnail_from_pdf
    with Image(filename="{}[0]".format(artifact.pdf_file.path), resolution=300) as img:
  File "/usr/local/lib/python3.8/site-packages/wand/image.py", line 9144, in __init__
    self.read(filename=filename)
  File "/usr/local/lib/python3.8/site-packages/wand/image.py", line 9815, in read
    self.raise_exception()
  File "/usr/local/lib/python3.8/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.PolicyError: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/421
ERROR 2021-12-17 16:15:35,002 basehttp 396 140215633041152 "POST /admin/website/publication/add/ HTTP/1.1" 500 145
```

**Comment by jonfroehlich** [comment]
Getting same issue on local dev environment now:

![image](https://user-images.githubusercontent.com/1621749/146676435-7ee75036-da8d-4dd3-9346-9a687d2c0dda.png)

**Comment by jonfroehlich** [comment]
OK, I fixed this on local dev by:

1. Opening an interactive bash shell of the Docker container: `docker exec -it makeabilitylabwebsite_website_1 bash`
2. Becoming root. I used the `su` command.
3. Opening `/etc/ImageMagick-6/policy.xml` as the above suggests. I used the `pico` editor, which I first installed as root by `apt-get install nano`
4. Commenting out the following in `policy.xml`:
    ```
    &lt;!-- disable ghostscript format types --&gt;
    &lt;!-- &lt;policy domain="coder" rights="none" pattern="PS" /&gt; --&gt;
    &lt;!-- &lt;policy domain="coder" rights="none" pattern="PS2" /&gt; --&gt;
    &lt;!-- &lt;policy domain="coder" rights="none" pattern="PS3" /&gt; --&gt;
    &lt;!-- &lt;policy domain="coder" rights="none" pattern="EPS" /&gt; --&gt;
   &lt;!-- &lt;policy domain="coder" rights="none" pattern="PDF" /&gt; --&gt;
   &lt;!-- &lt;policy domain="coder" rights="none" pattern="XPS" /&gt; --&gt;
    ```
5. Saving the `policy.xml` file

And things worked right away. I imagine we can replicate this on test and production. Need to talk to Jason.

**Comment by jonfroehlich** [comment]
Jason suggests that we create a new policy.xml file (that is edited correctly) and then update Dockerfile to copy over the policy.xml  to `/etc/ImageMagick-6/policy.xml`

Need to do it above line 58 (which is where we switch to user `apache`)

**Comment by jonfroehlich** [comment]
This is now happening on the -test server too:

```
DEBUG 2021-12-30 11:00:19,700 signals generate_and_save_thumbnail_from_pdf 396 140417697830656 Thumbnail does not exist, creating...
ERROR 2021-12-30 11:00:19,717 log log_response 396 140417697830656 Internal Server Error: /admin/website/publication/add/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1657, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1540, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1586, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1099, in save_model
    obj.save()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 787, in save_base
    post_save.send(
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/code/website/signals.py", line 42, in publication_post_save
    generate_and_save_thumbnail_from_pdf(pub, thumbnail_res)
  File "/code/website/signals.py", line 99, in generate_and_save_thumbnail_from_pdf
    with Image(filename="{}[0]".format(artifact.pdf_file.path), resolution=300) as img:
  File "/usr/local/lib/python3.8/site-packages/wand/image.py", line 9144, in __init__
    self.read(filename=filename)
  File "/usr/local/lib/python3.8/site-packages/wand/image.py", line 9815, in read
    self.raise_exception()
  File "/usr/local/lib/python3.8/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.PolicyError: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/421
ERROR 2021-12-30 11:00:19,726 basehttp log_message 396 140417697830656 "POST /admin/website/publication/add/ HTTP/1.1" 500 145
DEBUG 2021-12-30 11:00:20,404 autoreload tick 396 140418080241472 File /usr/local/lib/python3.8/_strptime.py first seen with mtime 1634116562.0
INFO 2021-12-30 11:01:29,432 basehttp log_message 396 140417689437952 "GET /news/40/ HTTP/1.1" 200 31118
DEBUG 2021-12-30 11:01:30,440 autoreload tick 396 140418080241472 File /usr/local/lib/python3.8/site-packages/easy_thumbnails/namers.py first seen with mtime 1639782523.0
```

Will try to fix it by using @mechanicjay's suggested fix above.

**Comment by jonfroehlich** [comment]
OK, I just added

```
# Copy over the new ImageMagick policy, see:
# https://github.com/makeabilitylab/makeabilitylabwebsite/issues/974
COPY imagemagick-policy.xml /etc/ImageMagick-6/policy.xml
```

to the Dockerfile but it doesn't seem to be working.

**Comment by jonfroehlich** [comment]
@mechanicjay verified that this is working on -test.
