### ISSUE TITLE
On Docker wsl2 setup, media folder does not initialize with StarWars figures

### ISSUE THREAD

**Issue by jonfroehlich** [makeabilitylab/makeabilitylabwebsite#985]
For some reason, on the Docker wsl2 setup, the media folder does not get initialized with content. Thus, if you try to add a new person, which requires some images at /code/media/images, then you'll receive an error.

```
website_1  | Internal Server Error: /admin/website/person/add/
website_1  | Traceback (most recent call last):
website_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
website_1  |     response = get_response(request)
website_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 126, in _get_response
website_1  |     response = self.process_exception_by_middleware(e, request)
website_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 124, in _get_response
website_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
website_1  |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 604, in wrapper
website_1  |     return self.admin_site.admin_view(view)(*args, **kwargs)
website_1  |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
website_1  |     response = view_func(request, *args, **kwargs)
website_1  |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
website_1  |     response = view_func(request, *args, **kwargs)
website_1  |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 223, in inner
website_1  |     return view(request, *args, **kwargs)
website_1  |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1648, in add_view
website_1  |     return self.changeform_view(request, None, form_url, extra_context)
website_1  |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 45, in _wrapper
website_1  |     return bound_method(*args, **kwargs)
website_1  |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
website_1  |     response = view_func(request, *args, **kwargs)
website_1  |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1532, in changeform_view
website_1  |     return self._changeform_view(request, object_id, form_url, extra_context)
website_1  |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1575, in _changeform_view
website_1  |     self.save_model(request, new_object, form, not add)
website_1  |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1091, in save_model
website_1  |     obj.save()
website_1  |   File "/code/website/models/person.py", line 350, in save
website_1  |     star_wars_dir = os.path.join(dir, get_random_starwars(dir))
website_1  |   File "/code/website/models/person.py", line 395, in get_random_starwars
website_1  |     images = [f for f in os.listdir(direc) if isimage(f)]
website_1  | FileNotFoundError: [Errno 2] No such file or directory: 'media/images/StarWarsFiguresFullSquare/Rebels'
```

Digging into this, I found that the media folder was empty in the container. I have not seen this problem on other dev setups.

```
$ docker exec -it makeabilitylabwebsite_website_1 bash

apache@43cd75e1d80c:/code/media$ pwd
/code/media
apache@43cd75e1d80c:/code/media$ ls -al
total 8
drwxrwxrwx  2 1000 1000 4096 Dec 19 13:27 .
drwxr-xr-x 17 1000 1000 4096 Dec 18 00:53 ..
```

To fix this, I followed [these instructions](https://www.arungudelli.com/tutorial/docker/copy-files-folders-from-host-to-docker-container/) on how to copy content from your local file system into the Docker container.

```
$ docker ps
CONTAINER ID   IMAGE                           COMMAND                  CREATED        STATUS         PORTS                      NAMES
43cd75e1d80c   makeabilitylabwebsite_website   "./docker-entrypoint…"   44 hours ago   Up 8 minutes   127.0.0.1:8571->8000/tcp   makeabilitylabwebsite_website_1
d696eff6cb55   postgres                        "docker-entrypoint.s…"   44 hours ago   Up 8 minutes   0.0.0.0:59853->5432/tcp    makeabilitylabwebsite_db_1

$ docker cp media makeabilitylabwebsite_website_1:/code/.
```

Then, to check this, I went back to the container shell:

```
$ docker exec -it makeabilitylabwebsite_website_1 bash

apache@43cd75e1d80c:/code$ cd media
apache@43cd75e1d80c:/code/media$ ls -al
total 12
drwxrwxrwx  3 1000 1000 4096 Dec 17 17:26 .
drwxr-xr-x 17 1000 1000 4096 Dec 18 00:53 ..
drwxrwxrwx  3 1000 1000 4096 Dec 17 17:26 images
```

And then things work!

**Comment by jonfroehlich** [comment]
Interestingly, once I changed `media` to 777 permissions, the Star Wars figures got copied over automatically.

**Comment by jonfroehlich** [comment]
Hmm, on the -test and production servers, we map the `/code/media` directory to the filesystem. How would we duplicate this in our local dev setup? Need to ask @mechanicjay.

![image](https://user-images.githubusercontent.com/1621749/147780607-7a9c8452-f1f1-4da2-866a-f9c03d9438ed.png)

**Comment by jonfroehlich** [comment]
This is related to setting permissions in the linux filesystem and has been resolved.

![image](https://github.com/makeabilitylab/makeabilitylabwebsite/assets/1621749/fa0f5a3a-4400-4ef5-84b4-11b22669f6f7)

See also: 
https://stackoverflow.com/questions/69575151/permissionerror-errno-13-permission-denied-on-windows-with-wsl2-and-docker
